### ISSUE TITLE
Why is GRAIL not included?

### ISSUE THREAD

**Issue by cmcuza** [itouchz/awesome-deep-time-series-representations#1]
Hi, 

First of all, thanks for such a nice, well-maintained, repository. 
Looking into the "Accompanying Paper" I noticed that paper [1] is not included. I wonder if I am mistaken in believing that it should be included or if there is any specific reason why it is not. 

Thanks in advance and regards,
[1] Paparrizos, John, and Michael J. Franklin. "Grail: efficient time-series representation learning." Proceedings of the VLDB Endowment 12.11 (2019): 1762-1777. https://dl.acm.org/doi/pdf/10.14778/3342263.3342648

**Comment by itouchz** [comment]
Hi,

Thank you for your question. We were fully aware of the GRAIL paper; however, we did not include it in our work because it is not a deep learning/neural network-based approach, as outlined in Section 1.2 of our paper.

**Comment by cmcuza** [comment]
Hi,

I see, thanks for the prompt answer.
